baseURL: http://photos.chmouel.com/
languageCode: en-UK
title: Chmouel's Photos
theme: chmouphotos

minify:
  disableXML: true
  minifyOutput: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
rssLimit: 25

outputs:
  home:
    - HTML
    - RSS
    - JSON
